[package]
name = "pipefilter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.23.2"
regex = "1.5.6"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
